# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'status.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(667, 483)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_realtime = QtWidgets.QCheckBox(Form)
        self.checkBox_realtime.setChecked(True)
        self.checkBox_realtime.setObjectName("checkBox_realtime")
        self.horizontalLayout_2.addWidget(self.checkBox_realtime)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMaximumSize(QtCore.QSize(50, 50))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.comboBox_sat = QtWidgets.QComboBox(Form)
        self.comboBox_sat.setObjectName("comboBox_sat")
        self.comboBox_sat.addItem("")
        self.comboBox_sat.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_sat)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_recv_time = QtWidgets.QComboBox(Form)
        self.comboBox_recv_time.setMinimumSize(QtCore.QSize(180, 27))
        self.comboBox_recv_time.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_recv_time.setObjectName("comboBox_recv_time")
        self.horizontalLayout.addWidget(self.comboBox_recv_time)
        self.pushButton_refresh = QtWidgets.QPushButton(Form)
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.horizontalLayout.addWidget(self.pushButton_refresh)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(14)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 6, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(8)
        self.tableWidget_2.setRowCount(14)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(6, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(7, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(8, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(9, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(10, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(10, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(11, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(11, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(12, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(12, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(13, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(13, 6, item)
        self.tableWidget_2.horizontalHeader().setVisible(False)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.horizontalHeader().setHighlightSections(True)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.verticalHeader().setHighlightSections(True)
        self.verticalLayout_2.addWidget(self.tableWidget_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "01H工参"))
        self.checkBox_realtime.setText(_translate("Form", "显示最新一包并实时更新"))
        self.label_2.setText(_translate("Form", "航天器ID"))
        self.comboBox_sat.setItemText(0, _translate("Form", "A机"))
        self.comboBox_sat.setItemText(1, _translate("Form", "B机"))
        self.label.setText(_translate("Form", "接收时间"))
        self.pushButton_refresh.setText(_translate("Form", "Refresh"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Form", "13"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "项目1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "值1"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "项目2"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "值2"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "项目3"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "值3"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "项目4"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "值4"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "配置状态"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Form", "数字信号强度指示1"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("Form", "RF发送抛弃包计数"))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("Form", "当前发送文件序号"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", "工作模式"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("Form", "数字信号强度指示2"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("Form", "RF接收包计数"))
        item = self.tableWidget.item(1, 6)
        item.setText(_translate("Form", "当前发送文件长度"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Form", "通道状态标识1"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("Form", "模拟信号强度指示"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("Form", "RF接收错误包计数"))
        item = self.tableWidget.item(2, 6)
        item.setText(_translate("Form", "当前发送文件校验值"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Form", "通道状态标识2"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("Form", "PCB温度1"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("Form", "RF接收执行错误计数"))
        item = self.tableWidget.item(3, 6)
        item.setText(_translate("Form", "FTP发送数据块大小"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("Form", "通道状态标识3"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("Form", "PCB温度2"))
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("Form", "RF接收纠错失败计数"))
        item = self.tableWidget.item(4, 6)
        item.setText(_translate("Form", "FTP发送成功包数"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("Form", "通道状态标识4"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("Form", "剩余存储空间"))
        item = self.tableWidget.item(5, 4)
        item.setText(_translate("Form", "RF最近一条指令"))
        item = self.tableWidget.item(5, 6)
        item.setText(_translate("Form", "FTP发送缺失包数"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("Form", "+5V接收电流"))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("Form", "CPU占用率"))
        item = self.tableWidget.item(6, 4)
        item.setText(_translate("Form", "RF指令执行情况"))
        item = self.tableWidget.item(6, 6)
        item.setText(_translate("Form", "读取数据包计数"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("Form", "+5V接收电压"))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("Form", "CAN发送包计数"))
        item = self.tableWidget.item(7, 4)
        item.setText(_translate("Form", "FTP当前接收文件序号"))
        item = self.tableWidget.item(7, 6)
        item.setText(_translate("Form", "注入数据计数"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("Form", "+5V发射电流"))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("Form", "CAN接收包计数"))
        item = self.tableWidget.item(8, 4)
        item.setText(_translate("Form", "FTP当前接收文件长度"))
        item = self.tableWidget.item(8, 6)
        item.setText(_translate("Form", "复位计数"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("Form", "+5V发射电压"))
        item = self.tableWidget.item(9, 2)
        item.setText(_translate("Form", "CAN错误包计数"))
        item = self.tableWidget.item(9, 4)
        item.setText(_translate("Form", "FTP当前接收文件校验值"))
        item = self.tableWidget.item(9, 6)
        item.setText(_translate("Form", "复位标识"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("Form", "+3.3V电流"))
        item = self.tableWidget.item(10, 2)
        item.setText(_translate("Form", "CAN执行错误计数"))
        item = self.tableWidget.item(10, 4)
        item.setText(_translate("Form", "FTP接收数据块大小"))
        item = self.tableWidget.item(10, 6)
        item.setText(_translate("Form", "系统状态标识"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("Form", "+3.3V电压"))
        item = self.tableWidget.item(11, 2)
        item.setText(_translate("Form", "CAN最近一条指令"))
        item = self.tableWidget.item(11, 4)
        item.setText(_translate("Form", "FTP接收成功包数"))
        item = self.tableWidget.item(11, 6)
        item.setText(_translate("Form", "ARM运行时间"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("Form", "接收频偏1"))
        item = self.tableWidget.item(12, 2)
        item.setText(_translate("Form", "CAN指令执行情况"))
        item = self.tableWidget.item(12, 4)
        item.setText(_translate("Form", "FTP接收缺失包数"))
        item = self.tableWidget.item(12, 6)
        item.setText(_translate("Form", "AVR运行时间"))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("Form", "接收频偏2"))
        item = self.tableWidget.item(13, 2)
        item.setText(_translate("Form", "RF发送包计数"))
        item = self.tableWidget.item(13, 4)
        item.setText(_translate("Form", "目标CAN节点地址"))
        item = self.tableWidget.item(13, 6)
        item.setText(_translate("Form", "保留"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "A机"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget_2.verticalHeaderItem(9)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget_2.verticalHeaderItem(10)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget_2.verticalHeaderItem(11)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget_2.verticalHeaderItem(12)
        item.setText(_translate("Form", "13"))
        item = self.tableWidget_2.verticalHeaderItem(13)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "项目1"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "值1"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "项目2"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "值2"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Form", "项目3"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Form", "值3"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("Form", "项目4"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("Form", "值4"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("Form", "配置状态"))
        item = self.tableWidget_2.item(0, 2)
        item.setText(_translate("Form", "数字信号强度指示1"))
        item = self.tableWidget_2.item(0, 4)
        item.setText(_translate("Form", "RF发送抛弃包计数"))
        item = self.tableWidget_2.item(0, 6)
        item.setText(_translate("Form", "当前发送文件序号"))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("Form", "工作模式"))
        item = self.tableWidget_2.item(1, 2)
        item.setText(_translate("Form", "数字信号强度指示2"))
        item = self.tableWidget_2.item(1, 4)
        item.setText(_translate("Form", "RF接收包计数"))
        item = self.tableWidget_2.item(1, 6)
        item.setText(_translate("Form", "当前发送文件长度"))
        item = self.tableWidget_2.item(2, 0)
        item.setText(_translate("Form", "通道状态标识1"))
        item = self.tableWidget_2.item(2, 2)
        item.setText(_translate("Form", "模拟信号强度指示"))
        item = self.tableWidget_2.item(2, 4)
        item.setText(_translate("Form", "RF接收错误包计数"))
        item = self.tableWidget_2.item(2, 6)
        item.setText(_translate("Form", "当前发送文件校验值"))
        item = self.tableWidget_2.item(3, 0)
        item.setText(_translate("Form", "通道状态标识2"))
        item = self.tableWidget_2.item(3, 2)
        item.setText(_translate("Form", "PCB温度1"))
        item = self.tableWidget_2.item(3, 4)
        item.setText(_translate("Form", "RF接收执行错误计数"))
        item = self.tableWidget_2.item(3, 6)
        item.setText(_translate("Form", "FTP发送数据块大小"))
        item = self.tableWidget_2.item(4, 0)
        item.setText(_translate("Form", "通道状态标识3"))
        item = self.tableWidget_2.item(4, 2)
        item.setText(_translate("Form", "PCB温度2"))
        item = self.tableWidget_2.item(4, 4)
        item.setText(_translate("Form", "RF接收纠错失败计数"))
        item = self.tableWidget_2.item(4, 6)
        item.setText(_translate("Form", "FTP发送成功包数"))
        item = self.tableWidget_2.item(5, 0)
        item.setText(_translate("Form", "通道状态标识4"))
        item = self.tableWidget_2.item(5, 2)
        item.setText(_translate("Form", "剩余存储空间"))
        item = self.tableWidget_2.item(5, 4)
        item.setText(_translate("Form", "RF最近一条指令"))
        item = self.tableWidget_2.item(5, 6)
        item.setText(_translate("Form", "FTP发送缺失包数"))
        item = self.tableWidget_2.item(6, 0)
        item.setText(_translate("Form", "+5V接收电流"))
        item = self.tableWidget_2.item(6, 2)
        item.setText(_translate("Form", "CPU占用率"))
        item = self.tableWidget_2.item(6, 4)
        item.setText(_translate("Form", "RF指令执行情况"))
        item = self.tableWidget_2.item(6, 6)
        item.setText(_translate("Form", "读取数据包计数"))
        item = self.tableWidget_2.item(7, 0)
        item.setText(_translate("Form", "+1V内核电压"))
        item = self.tableWidget_2.item(7, 2)
        item.setText(_translate("Form", "CAN发送包计数"))
        item = self.tableWidget_2.item(7, 4)
        item.setText(_translate("Form", "FTP当前接收文件序号"))
        item = self.tableWidget_2.item(7, 6)
        item.setText(_translate("Form", "注入数据计数"))
        item = self.tableWidget_2.item(8, 0)
        item.setText(_translate("Form", "+5V发射电流"))
        item = self.tableWidget_2.item(8, 2)
        item.setText(_translate("Form", "CAN接收包计数"))
        item = self.tableWidget_2.item(8, 4)
        item.setText(_translate("Form", "FTP当前接收文件长度"))
        item = self.tableWidget_2.item(8, 6)
        item.setText(_translate("Form", "复位计数"))
        item = self.tableWidget_2.item(9, 0)
        item.setText(_translate("Form", "+1.8V IO电压"))
        item = self.tableWidget_2.item(9, 2)
        item.setText(_translate("Form", "CAN错误包计数"))
        item = self.tableWidget_2.item(9, 4)
        item.setText(_translate("Form", "FTP当前接收文件校验值"))
        item = self.tableWidget_2.item(9, 6)
        item.setText(_translate("Form", "复位标识"))
        item = self.tableWidget_2.item(10, 0)
        item.setText(_translate("Form", "+3.3V电流"))
        item = self.tableWidget_2.item(10, 2)
        item.setText(_translate("Form", "CAN执行错误计数"))
        item = self.tableWidget_2.item(10, 4)
        item.setText(_translate("Form", "FTP接收数据块大小"))
        item = self.tableWidget_2.item(10, 6)
        item.setText(_translate("Form", "系统状态标识"))
        item = self.tableWidget_2.item(11, 0)
        item.setText(_translate("Form", "+1.5V DDR3电压"))
        item = self.tableWidget_2.item(11, 2)
        item.setText(_translate("Form", "CAN最近一条指令"))
        item = self.tableWidget_2.item(11, 4)
        item.setText(_translate("Form", "FTP接收成功包数"))
        item = self.tableWidget_2.item(11, 6)
        item.setText(_translate("Form", "ARM运行时间"))
        item = self.tableWidget_2.item(12, 0)
        item.setText(_translate("Form", "接收频偏1"))
        item = self.tableWidget_2.item(12, 2)
        item.setText(_translate("Form", "CAN指令执行情况"))
        item = self.tableWidget_2.item(12, 4)
        item.setText(_translate("Form", "FTP接收缺失包数"))
        item = self.tableWidget_2.item(12, 6)
        item.setText(_translate("Form", "AVR运行时间"))
        item = self.tableWidget_2.item(13, 0)
        item.setText(_translate("Form", "接收频偏2"))
        item = self.tableWidget_2.item(13, 2)
        item.setText(_translate("Form", "RF发送包计数"))
        item = self.tableWidget_2.item(13, 4)
        item.setText(_translate("Form", "目标CAN节点地址"))
        item = self.tableWidget_2.item(13, 6)
        item.setText(_translate("Form", "保留"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "B机"))


