# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'status.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(967, 617)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.checkBox_realtime = QtGui.QCheckBox(Form)
        self.checkBox_realtime.setChecked(True)
        self.checkBox_realtime.setObjectName(_fromUtf8("checkBox_realtime"))
        self.horizontalLayout_2.addWidget(self.checkBox_realtime)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit = QtGui.QLineEdit(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMaximumSize(QtCore.QSize(50, 50))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_2.addWidget(self.lineEdit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.comboBox_sat = QtGui.QComboBox(Form)
        self.comboBox_sat.setObjectName(_fromUtf8("comboBox_sat"))
        self.comboBox_sat.addItem(_fromUtf8(""))
        self.comboBox_sat.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox_sat)
        self.pushButton_refresh = QtGui.QPushButton(Form)
        self.pushButton_refresh.setObjectName(_fromUtf8("pushButton_refresh"))
        self.horizontalLayout.addWidget(self.pushButton_refresh)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_recv_time = QtGui.QComboBox(Form)
        self.comboBox_recv_time.setMinimumSize(QtCore.QSize(180, 27))
        self.comboBox_recv_time.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_recv_time.setObjectName(_fromUtf8("comboBox_recv_time"))
        self.horizontalLayout.addWidget(self.comboBox_recv_time)
        self.pushButton_inquire = QtGui.QPushButton(Form)
        self.pushButton_inquire.setObjectName(_fromUtf8("pushButton_inquire"))
        self.horizontalLayout.addWidget(self.pushButton_inquire)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tableWidget = QtGui.QTableWidget(self.tab)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(14)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(6, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(7, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(8, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(9, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(10, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(11, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(12, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(13, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(13, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(13, 6, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tableWidget_2 = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(8)
        self.tableWidget_2.setRowCount(14)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(6, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(6, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(6, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(7, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(7, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(7, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(8, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(8, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(8, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(9, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(9, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(9, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(9, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(10, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(10, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(10, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(10, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(11, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(11, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(11, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(11, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(12, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(12, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(12, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(12, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(13, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(13, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(13, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(13, 6, item)
        self.tableWidget_2.horizontalHeader().setVisible(False)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.horizontalHeader().setHighlightSections(True)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.verticalHeader().setHighlightSections(True)
        self.verticalLayout_2.addWidget(self.tableWidget_2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "01H工参", None))
        self.checkBox_realtime.setText(_translate("Form", "显示最新一包并实时更新", None))
        self.label_2.setText(_translate("Form", "航天器ID", None))
        self.label_3.setText(_translate("Form", "查询", None))
        self.comboBox_sat.setItemText(0, _translate("Form", "A机", None))
        self.comboBox_sat.setItemText(1, _translate("Form", "B机", None))
        self.pushButton_refresh.setText(_translate("Form", "Refresh", None))
        self.label.setText(_translate("Form", "接收时间", None))
        self.pushButton_inquire.setText(_translate("Form", "Inquire", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "3", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "4", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "5", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "6", None))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "7", None))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "8", None))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Form", "9", None))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Form", "10", None))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Form", "11", None))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Form", "12", None))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Form", "13", None))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Form", "14", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "项目1", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "值1", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "项目2", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "值2", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "项目3", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "值3", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "项目4", None))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "值4", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "配置状态", None))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Form", "数字信号强度指示1", None))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("Form", "RF发送抛弃包计数", None))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("Form", "目标CAN节点地址", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", "工作模式", None))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("Form", "数字信号强度指示2", None))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("Form", "RF接收包计数", None))
        item = self.tableWidget.item(1, 6)
        item.setText(_translate("Form", "当前发送文件序号", None))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Form", "通道状态标识1", None))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("Form", "模拟信号强度指示", None))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("Form", "RF接收错误包计数", None))
        item = self.tableWidget.item(2, 6)
        item.setText(_translate("Form", "当前发送文件长度", None))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Form", "通道状态标识2", None))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("Form", "PCB温度1", None))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("Form", "RF接收执行错误计数", None))
        item = self.tableWidget.item(3, 6)
        item.setText(_translate("Form", "当前发送文件校验值", None))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("Form", "发射增益高字节", None))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("Form", "PCB温度2", None))
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("Form", "RF接收纠错失败计数", None))
        item = self.tableWidget.item(4, 6)
        item.setText(_translate("Form", "FTP发送数据块大小", None))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("Form", "发射增益低字节", None))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("Form", "保留", None))
        item = self.tableWidget.item(5, 4)
        item.setText(_translate("Form", "RF最近一条指令", None))
        item = self.tableWidget.item(5, 6)
        item.setText(_translate("Form", "FTP发送成功包数", None))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("Form", "+5V接收电流", None))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("Form", "保留1", None))
        item = self.tableWidget.item(6, 4)
        item.setText(_translate("Form", "RF指令执行情况", None))
        item = self.tableWidget.item(6, 6)
        item.setText(_translate("Form", "FTP发送缺失包数", None))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("Form", "+5V接收电压", None))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("Form", "CAN发送包计数", None))
        item = self.tableWidget.item(7, 4)
        item.setText(_translate("Form", "FTP连续传输包数", None))
        item = self.tableWidget.item(7, 6)
        item.setText(_translate("Form", "读取数据包计数", None))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("Form", "+5V发射电流", None))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("Form", "CAN接收包计数", None))
        item = self.tableWidget.item(8, 4)
        item.setText(_translate("Form", "FTP当前接收文件编号", None))
        item = self.tableWidget.item(8, 6)
        item.setText(_translate("Form", "复位计数", None))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("Form", "+5V发射电压", None))
        item = self.tableWidget.item(9, 2)
        item.setText(_translate("Form", "CAN错误包计数", None))
        item = self.tableWidget.item(9, 4)
        item.setText(_translate("Form", "FTP当前接收文件长度", None))
        item = self.tableWidget.item(9, 6)
        item.setText(_translate("Form", "复位标识", None))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("Form", "+3.3V电流", None))
        item = self.tableWidget.item(10, 2)
        item.setText(_translate("Form", "CAN执行错误计数", None))
        item = self.tableWidget.item(10, 4)
        item.setText(_translate("Form", "FTP当前接收文件校验值", None))
        item = self.tableWidget.item(10, 6)
        item.setText(_translate("Form", "保留3", None))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("Form", "+3.3V电压", None))
        item = self.tableWidget.item(11, 2)
        item.setText(_translate("Form", "CAN最近一条指令", None))
        item = self.tableWidget.item(11, 4)
        item.setText(_translate("Form", "FTP接收数据块大小", None))
        item = self.tableWidget.item(11, 6)
        item.setText(_translate("Form", "ARM运行时间", None))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("Form", "接收频偏1", None))
        item = self.tableWidget.item(12, 2)
        item.setText(_translate("Form", "CAN指令执行情况", None))
        item = self.tableWidget.item(12, 4)
        item.setText(_translate("Form", "FTP接收成功包数", None))
        item = self.tableWidget.item(12, 6)
        item.setText(_translate("Form", "AVR运行时间", None))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("Form", "接收频偏2", None))
        item = self.tableWidget.item(13, 2)
        item.setText(_translate("Form", "RF发送包计数", None))
        item = self.tableWidget.item(13, 4)
        item.setText(_translate("Form", "FTP接收缺失包数", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "A机", None))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("Form", "1", None))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("Form", "2", None))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("Form", "3", None))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("Form", "4", None))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("Form", "5", None))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("Form", "6", None))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("Form", "7", None))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(_translate("Form", "8", None))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(_translate("Form", "9", None))
        item = self.tableWidget_2.verticalHeaderItem(9)
        item.setText(_translate("Form", "10", None))
        item = self.tableWidget_2.verticalHeaderItem(10)
        item.setText(_translate("Form", "11", None))
        item = self.tableWidget_2.verticalHeaderItem(11)
        item.setText(_translate("Form", "12", None))
        item = self.tableWidget_2.verticalHeaderItem(12)
        item.setText(_translate("Form", "13", None))
        item = self.tableWidget_2.verticalHeaderItem(13)
        item.setText(_translate("Form", "14", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "项目1", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "值1", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "项目2", None))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "值2", None))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Form", "项目3", None))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Form", "值3", None))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("Form", "项目4", None))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("Form", "值4", None))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("Form", "配置状态", None))
        item = self.tableWidget_2.item(0, 2)
        item.setText(_translate("Form", "数字信号强度指示1", None))
        item = self.tableWidget_2.item(0, 4)
        item.setText(_translate("Form", "RF发送抛弃包计数", None))
        item = self.tableWidget_2.item(0, 6)
        item.setText(_translate("Form", "当前发送文件序号", None))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("Form", "工作模式", None))
        item = self.tableWidget_2.item(1, 2)
        item.setText(_translate("Form", "数字信号强度指示2", None))
        item = self.tableWidget_2.item(1, 4)
        item.setText(_translate("Form", "RF接收包计数", None))
        item = self.tableWidget_2.item(1, 6)
        item.setText(_translate("Form", "当前发送文件长度", None))
        item = self.tableWidget_2.item(2, 0)
        item.setText(_translate("Form", "通道状态标识1", None))
        item = self.tableWidget_2.item(2, 2)
        item.setText(_translate("Form", "保留", None))
        item = self.tableWidget_2.item(2, 4)
        item.setText(_translate("Form", "RF接收错误包计数", None))
        item = self.tableWidget_2.item(2, 6)
        item.setText(_translate("Form", "当前发送文件校验值", None))
        item = self.tableWidget_2.item(3, 0)
        item.setText(_translate("Form", "保留", None))
        item = self.tableWidget_2.item(3, 2)
        item.setText(_translate("Form", "PCB温度1", None))
        item = self.tableWidget_2.item(3, 4)
        item.setText(_translate("Form", "RF接收执行错误计数", None))
        item = self.tableWidget_2.item(3, 6)
        item.setText(_translate("Form", "FTP发送数据块大小", None))
        item = self.tableWidget_2.item(4, 0)
        item.setText(_translate("Form", "接收速率", None))
        item = self.tableWidget_2.item(4, 2)
        item.setText(_translate("Form", "保留", None))
        item = self.tableWidget_2.item(4, 4)
        item.setText(_translate("Form", "RF最近一条指令", None))
        item = self.tableWidget_2.item(4, 6)
        item.setText(_translate("Form", "FTP发送成功包数", None))
        item = self.tableWidget_2.item(5, 0)
        item.setText(_translate("Form", "保留", None))
        item = self.tableWidget_2.item(5, 2)
        item.setText(_translate("Form", "剩余存储空间", None))
        item = self.tableWidget_2.item(5, 4)
        item.setText(_translate("Form", "RF指令执行情况", None))
        item = self.tableWidget_2.item(5, 6)
        item.setText(_translate("Form", "FTP发送缺失包数", None))
        item = self.tableWidget_2.item(6, 0)
        item.setText(_translate("Form", "保留", None))
        item = self.tableWidget_2.item(6, 2)
        item.setText(_translate("Form", "CPU占用率", None))
        item = self.tableWidget_2.item(6, 4)
        item.setText(_translate("Form", "FTP连续传输包数", None))
        item = self.tableWidget_2.item(6, 6)
        item.setText(_translate("Form", "读取数据包计数", None))
        item = self.tableWidget_2.item(7, 0)
        item.setText(_translate("Form", "+1V内核电压", None))
        item = self.tableWidget_2.item(7, 2)
        item.setText(_translate("Form", "CAN发送包计数", None))
        item = self.tableWidget_2.item(7, 4)
        item.setText(_translate("Form", "FTP当前接收文件编号", None))
        item = self.tableWidget_2.item(7, 6)
        item.setText(_translate("Form", "保留", None))
        item = self.tableWidget_2.item(8, 0)
        item.setText(_translate("Form", "保留", None))
        item = self.tableWidget_2.item(8, 2)
        item.setText(_translate("Form", "CAN接收包计数", None))
        item = self.tableWidget_2.item(8, 4)
        item.setText(_translate("Form", "FTP当前接收文件长度", None))
        item = self.tableWidget_2.item(8, 6)
        item.setText(_translate("Form", "复位计数", None))
        item = self.tableWidget_2.item(9, 0)
        item.setText(_translate("Form", "+1.8V IO电压", None))
        item = self.tableWidget_2.item(9, 2)
        item.setText(_translate("Form", "CAN错误包计数", None))
        item = self.tableWidget_2.item(9, 4)
        item.setText(_translate("Form", "FTP当前接收文件校验值", None))
        item = self.tableWidget_2.item(9, 6)
        item.setText(_translate("Form", "复位标识", None))
        item = self.tableWidget_2.item(10, 0)
        item.setText(_translate("Form", "保留", None))
        item = self.tableWidget_2.item(10, 2)
        item.setText(_translate("Form", "CAN执行错误计数", None))
        item = self.tableWidget_2.item(10, 4)
        item.setText(_translate("Form", "FTP接收数据块大小", None))
        item = self.tableWidget_2.item(10, 6)
        item.setText(_translate("Form", "ARM运行时间", None))
        item = self.tableWidget_2.item(11, 0)
        item.setText(_translate("Form", "+1.5V DDR3电压", None))
        item = self.tableWidget_2.item(11, 2)
        item.setText(_translate("Form", "CAN最近一条指令", None))
        item = self.tableWidget_2.item(11, 4)
        item.setText(_translate("Form", "FTP接收成功包数", None))
        item = self.tableWidget_2.item(12, 0)
        item.setText(_translate("Form", "接收频偏1", None))
        item = self.tableWidget_2.item(12, 2)
        item.setText(_translate("Form", "CAN指令执行情况", None))
        item = self.tableWidget_2.item(12, 4)
        item.setText(_translate("Form", "FTP接收缺失包数", None))
        item = self.tableWidget_2.item(13, 0)
        item.setText(_translate("Form", "接收频偏2", None))
        item = self.tableWidget_2.item(13, 2)
        item.setText(_translate("Form", "RF发送包计数", None))
        item = self.tableWidget_2.item(13, 4)
        item.setText(_translate("Form", "目标CAN节点地址", None))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "B机", None))

